baseURL = "https://behouba.github.io/"
languageCode = "en-us"
title = "Behouba Manassé K"
canonifyurls = true

[module]
  [[module.imports]]
    path = "github.com/manid2/hugo-xterm"

theme = "hugo-xterm"

[pagination]
  pagerSize = 10

[permalinks]
  posts = "/:year/:month/:title"

[params]
  centerTheme = true
  showMenuItems = true
  favicon = "/images/favicons/favicon.ico"
  showBreadCrumbs = true
  toc = true
  copyrightUserUrl = "https://github.com/behouba"
  copyrightUserText = "behouba"


[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/behouba"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/behouba_"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false