baseURL = "https://behouba.github.io/"
languageCode = "en-us"
title = "Behouba Manassé K"
theme = "ink-free"
paginate = 7

copyright = "© Behouba Manassé Kouamé"
# Demo only
#ignoreErrors = ["error-missing-instagram-accesstoken"]

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "Software engineering, Linux, cloud computing, and random topics I enjoy."

	# Optional 64x64 avatar image.
	#avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	featherIconsCDN = false
	mermaidCDN = "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs"

	# Site color - dark/light/auto
	mode = "auto"

	# Enable a table of contents:
	# Either "static"/true, "floating", "both", or "none" (default: static)
	# The floating TOC dissapears on mobile and adds 200px vertical space
	toc = "both"
	# Whether to truncate everything but H1/H2 headings if the last element in a TOC isn't visible. Enabled by default
	enableTocTrunate = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	# For statistics, we can compare the total word count against a book of your choice
	statisticsEnabled = true
	referenceBookWords = 11500.0
	referenceBook = "The Metamorphosis"
	referenceAuthor = "Franz Kafka"


[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/behouba"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/behouba_"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
